[package]
name = "chatbot-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12.4"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15.7"
async-openai = { version = "0.26.0" }

